# Generated by Django 5.0.2 on 2024-03-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_hintversion_oldversionmetadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OldVersionMetadata',
            new_name='DownloadFileMetadata',
        ),
    ]
